### PR TITLE
Update to VS '15' project files. Fix tests. Fix warnings. 

### PR DESCRIPTION
**Pull request by ericwj**
Update to VS '15' project files.
Updated all references to Newtonsoft.Json to version 10.
DelegateCommand.Execute is now void. It cannot be awaited or .Wait()'ed and tests using it need no longer be async either.
Visual Studio Test Framework now lives in another namespace and is implemented in a different SDK and using different dependencies. No code changes are needed apart from the namespace change.
Fix test SaveEntity_SavesEntity crashing on `new ResourceLoader()` in [ErrorMessagesHelper#L10](https://github.com/PrismLibrary/Prism-Samples-Windows/blob/db5bfd9b132e50ab0e78e28818b9f6a21e7df629/AdventureWorks.Shopper/AdventureWorks.UILogic/Services/ErrorMessagesHelper.cs#L10).
Added some pragma's, removed unused declarations and so forth to remove all warnings except the [Deprecated] warning about the `ResourceLoader(string)` constructor.

### CODE REVIEW

**Comment by ericwj** [comment]
#19

**Comment by bartlannoeye** [comment]
With the release of FCU and VS2017 being more stable, it's time to look forward. Thanks for the PR.

**Comment by ericwj** [comment]
FCU?

**Comment by dansiegel** [comment]
Fall Creators Update

**Comment by ericwj** [comment]
Ah ofc. Well my investment in Prism was a waste of time. It should've had premium Windows support throughout and it baffles me you had its priority dropped.

**Comment by bartlannoeye** [comment]
Sorry to hear your opinion @ericwj. Since Prism was turned over to the community (over 2 years ago), it's the task of the community to step in and help out. Every single person helping out does this in his/her spare time (including the "core" team). We're very thankful for every bit of help we get.

The reason for this particular pull request to be open that long was that we were still supporting back until the initial version (and thus running on Visual Studio 2015). With the latest update, we made the decision to move forward to Visual Studio 2017.

**Comment by brianlagunas** [comment]
@ericwj It's never been a priority because we have a realistic understanding of the current market and where we should be placing our efforts, and it's not UWP.  Hell, even Microsoft doesn't have "premium support" for it's own platform.  The current state of it's tooling is a mess.

Since you feel using Prism for UWP has wasted your time, I will offer you a full refund of your purchase price.

**Comment by ericwj** [comment]
Haha well thanks. But you were given a sizeable investment done by Microsoft and it appears wrong to me that you then sort of turned your back on them.

**Comment by brianlagunas** [comment]
Wow... you have absolutely no idea what you are talking about. I am done discussing this with you because you are not informed enough to have a discussion on this topic.  I will leave you with this, MS turned their back on the Prism community and were going to kill it.  I saved it.

**Comment by ericwj** [comment]
Well you got all their code in the process.

**Pull request merged**
