### PR TITLE
Updated AdventureWorks reference implementation to use Prism.Unity 6 and converted it to a UWA.

### PR DESCRIPTION
**Pull request by ali-hk**
One of the major strengths of Prism IMO is the wealth of documentation and the thorough and complete sample that was provided in the form of the AdventureWorks Shopper reference implementation. As such I ported the reference implementation over to use Prism.Unity 6 and converted it to a UWA. I also cleaned up the styling and switched out some of the concepts with their Win 10 equivalents including VisualStateTriggers.

In the future the following still needs to be done:
- Replace the settings flyouts since they're gone in UWA
- Port over Windows Phone version of implementation
- Convert Validation code to new implementation
- Possibly switch to using x:Bind

### CODE REVIEW

**Comment by bartlannoeye** [comment]
You beat us to it :smile: , that's some great effort ! As soon as we find some time, we'll review it and pull it in. Thanks a lot.

**Comment by briannoyes** [comment]
Dude, you are my hero. This has been on my ToDo list and I really wanted to get it done to show in a session at DEVIntersection this week but have not had time. Now I can and will give due credit to our community heros that are helping move Prism 6 forward.

@bartlannoeye I'll get this reviewed and pulled in by mid-day tomorrow.

THANK YOU.

**Comment by ali-hk** [comment]
No problem :) I love Prism, so I'll do anything I can to help out.
One caveat, the Release build crashes or fails to retrieve data from the service depending on what version of the .NET Native tools you have installed due to a bug in .NET Native. I figured since this is a reference implementation that's not getting submitted to the Store that's ok for now until I figure out the appropriate solution/workaround.

**Comment by briannoyes** [comment]
Could I get your Twitter handle so I can give due credit once I merge it and tweet about it?

**Comment by ali-hk** [comment]
Sure, it's @AlexMSFT. Thanks :)

**Comment by briannoyes** [comment]
Thanks again for doing the bulk of the leg work. Just checked in and made a few changes - removed the duplicate validation infrastructure classes that are part of Prism.Windows now. Re-enabled DataAnnotations on model objects (they commented those out in the 2.0 release because of no data annotations on WinPhone 8.1), and cleaned up the copyright notices.

**Pull request merged**
