### PR TITLE
Added api README.md and default controller

### PR DESCRIPTION
**Pull request by JamieHouston**
Added quick readme so people know to run the api.

### CODE REVIEW

**Comment by bartlannoeye** [comment]
Is it possible that your readme file is one level too deep?

**Comment by JamieHouston** [comment]
Yes! I'll fix it.

A related question- I had to redo the commit because a line in the .gitattributes file (\* text=auto) makes it so cloning the repo (on osx or Windows) changes all the line endings. Is that on purpose? I had to comment out that line (but didn't commit it)

**Comment by JamieHouston** [comment]
@bartlannoeye I moved it up.  Thanks for pointing that out.

**Comment by bartlannoeye** [comment]
Thanks !

**Pull request merged**
